version: 2

tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --no-color ${INPUT}'
    lint-formats:
      - '    %f:%l:%c: %m'
    lint-stdin: true

  lua-luafmt: &lua-luafmt
    format-command: 'luafmt --indent-count 2 --stdin ${INPUT}'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename ${INPUT}'
    format-stdin: true

  vim-vint: &vim-vint
    lint-command: 'vint --enable-neovim --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  yaml:
    - <<: *yaml-yamllint

  sh:
    - <<: *sh-shellcheck

  lua:
    - <<: *lua-luacheck
    - <<: *lua-luafmt

  python:
    - <<: *python-flake8

  javascript:
    - <<: *eslint_d

  typescript:
    - <<: *eslint_d

  javascriptreact:
    - <<: *eslint_d

  typescriptreact:
    - <<: *eslint_d

  vim:
    - <<: *vim-vint
